//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error Сообщение об ошибках
type Error struct {
	Message *string `json:"message,omitempty"`
}

// Event Event
type Event struct {
	// CreatedAt Когда создал
	CreatedAt *openapi_types.Date `json:"created_at,omitempty"`

	// Description Описание
	Description *string `json:"description,omitempty"`

	// Id ID
	Id *int `json:"id,omitempty"`

	// Name Название
	Name *string `json:"name,omitempty"`

	// Owner Кто создал
	Owner *string `json:"owner,omitempty"`

	// WhenOccurs Когда произойдет
	WhenOccurs *openapi_types.Date `json:"when_occurs,omitempty"`

	// WhenRemind Когда напомнить
	WhenRemind *openapi_types.Date `json:"when_remind,omitempty"`
}

// DeleteEventJSONBody defines parameters for DeleteEvent.
type DeleteEventJSONBody struct {
	// Id ID
	Id *int `json:"id,omitempty"`
}

// CreateNewEventJSONBody defines parameters for CreateNewEvent.
type CreateNewEventJSONBody struct {
	// CreatedAt Когда создал
	CreatedAt *openapi_types.Date `json:"created_at,omitempty"`

	// Description Описание
	Description *string `json:"description,omitempty"`

	// Name Название
	Name *string `json:"name,omitempty"`

	// Owner Кто создал
	Owner *string `json:"owner,omitempty"`

	// WhenOccurs Когда произойдет
	WhenOccurs *openapi_types.Date `json:"when_occurs,omitempty"`

	// WhenRemind Когда напомнить
	WhenRemind *openapi_types.Date `json:"when_remind,omitempty"`
}

// EditEventJSONBody defines parameters for EditEvent.
type EditEventJSONBody struct {
	// CreatedAt Когда создал
	CreatedAt *openapi_types.Date `json:"created_at,omitempty"`

	// Description Описание
	Description *string `json:"description,omitempty"`

	// Id ID
	Id *int `json:"id,omitempty"`

	// Name Название
	Name *string `json:"name,omitempty"`

	// Owner Кто создал
	Owner *string `json:"owner,omitempty"`

	// WhenOccurs Когда произойдет
	WhenOccurs *openapi_types.Date `json:"when_occurs,omitempty"`

	// WhenRemind Когда напомнить
	WhenRemind *openapi_types.Date `json:"when_remind,omitempty"`
}

// DeleteEventJSONRequestBody defines body for DeleteEvent for application/json ContentType.
type DeleteEventJSONRequestBody DeleteEventJSONBody

// CreateNewEventJSONRequestBody defines body for CreateNewEvent for application/json ContentType.
type CreateNewEventJSONRequestBody CreateNewEventJSONBody

// EditEventJSONRequestBody defines body for EditEvent for application/json ContentType.
type EditEventJSONRequestBody EditEventJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Удаление события
	// (DELETE /events)
	DeleteEvent(w http.ResponseWriter, r *http.Request)
	// Получить массив с информацией о событиях
	// (GET /events)
	GetEventsList(w http.ResponseWriter, r *http.Request)
	// Создать новое событие
	// (POST /events)
	CreateNewEvent(w http.ResponseWriter, r *http.Request)
	// Изменение информации о событии
	// (PUT /events)
	EditEvent(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteEvent operation middleware
func (siw *ServerInterfaceWrapper) DeleteEvent(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetEventsList operation middleware
func (siw *ServerInterfaceWrapper) GetEventsList(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateNewEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateNewEvent(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNewEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// EditEvent operation middleware
func (siw *ServerInterfaceWrapper) EditEvent(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EditEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("DELETE "+options.BaseURL+"/events", wrapper.DeleteEvent)
	m.HandleFunc("GET "+options.BaseURL+"/events", wrapper.GetEventsList)
	m.HandleFunc("POST "+options.BaseURL+"/events", wrapper.CreateNewEvent)
	m.HandleFunc("PUT "+options.BaseURL+"/events", wrapper.EditEvent)

	return m
}
